application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /
  static_files: ./templates/sitehome.html
  upload: ./templates/sitehome.html
 
- url: /home.*
  script: main.application
  login: required
  auth_fail_action: redirect

libraries:
- name: django
  version: "1.4"
